---
title: "Evaluation report for `r params$code`/`r params$model`/`r params$conf`"
author: "Victor Granda / Miquel De Cáceres"
date: "`r Sys.time()`"
params:
  wd: '/home/miquel/OneDrive/Professional/Recerca/MedfateValidation/'
  code: 'FRAPUE'
  model: 'spwb'
  conf: 'basic'
output:
  html_document:
    df_print: paged
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_knit$set(root.dir = params$wd)

library(medfate)
library(medfatereports)
library(dplyr)
library(ggplot2)
```

```{r data, message=FALSE, warning=FALSE}

control <- yaml::yaml.load_file(system.file("yaml_configurations", paste0(params$conf, ".yaml"),
                                          package = "medfatereports"))

out_path <- file.path('Output', packageVersion('medfate')[[1]], params$model, params$conf, params$code)
out_plots <- file.path(out_path, 'Plots')
if (!dir.exists(out_plots)) {
  dir.create(out_plots, recursive = TRUE)
}
out_evalplots <- file.path(out_path, 'EvaluationPlots')
if (!dir.exists(out_evalplots)) {
  dir.create(out_evalplots, recursive = TRUE)
}

site_data <- load_list(params$code)

eval_REW <- "SWC" %in% names(site_data$measuredData)
```

# General Info

```{r gen_info}
data.frame(
    Pkg_version  = as.character(packageVersion('medfate')),
    Site = params$code,
    Model = params$model,
    Configuration = params$conf,
    Date = format(Sys.Date())
  )
```

## Remarks

```{r remarks, max.print=10}
site_data$remarks
```


# Run Model

```{r simple_model, eval=TRUE, message=FALSE}
soil_object <- soil(site_data$soilData, VG_PTF = "Toth")

if(params$model=="spwb") {
  input_object <- medfate::forest2spwbInput(site_data$forest_object1, 
                                            soil_object, 
                                            site_data$sp_params, 
                                            control)
  input_object <- modifyCohortParams(input_object, site_data$customParams)
  res <- spwb(input_object,
              site_data$meteoData, 
              latitude = site_data$terrainData$latitude, 
              elevation = site_data$terrainData$elevation, 
              slope = site_data$terrainData$slope, 
              aspect = site_data$terrainData$aspect)
} else if(params$model=="growth") {
  input_object <- medfate::forest2growthInput(site_data$forest_object1, 
                                            soil_object, 
                                            site_data$sp_params, 
                                            control)
  input_object <- modifyCohortParams(input_object, site_data$customParams)
  res <- growth(input_object,
              site_data$meteoData, 
              latitude = site_data$terrainData$latitude, 
              elevation = site_data$terrainData$elevation, 
              slope = site_data$terrainData$slope, 
              aspect = site_data$terrainData$aspect)
}
```


```{r}
# saving result
file_name <- file.path(out_path,
                       paste0('simulation_result.rds'))
saveRDS(res, file = file_name)
paste0("Model output file: ", file_name)
```
# Output plots

## PET & precipitation

```{r eval = params$model=="spwb", fig.height=6, fig.width=8}
type <- "PET_Precipitation"
p <-plot(res, type= type)
ggplot2::ggsave(filename = file.path(out_plots, paste0(type, ".png")),
                plot = p)
p
```



## Evapotranspiration
```{r eval = params$model=="spwb", fig.height=6, fig.width=8}
type <- "Evapotranspiration"
p <-plot(res, type= type)
ggplot2::ggsave(filename = file.path(out_plots, paste0(type, ".png")),
                plot = p)
p
```

## Soil moisture content
```{r eval = params$model=="spwb", fig.height=6, fig.width=8}
type <- "SoilTheta"
p <-plot(res, type= type)
ggplot2::ggsave(filename = file.path(out_plots, paste0(type, ".png")),
                plot = p)
p
```

## Plant LAI
```{r eval = params$model=="spwb", fig.height=6, fig.width=8}
type <- "PlantLAI"
p <-plot(res, type= type, bySpecies = TRUE)
ggplot2::ggsave(filename = file.path(out_plots, paste0(type, ".png")),
                plot = p)
p
```


## Transpiration per leaf
```{r eval = params$model=="spwb", fig.height=6, fig.width=8}
type <- "TranspirationPerLeaf"
p <-plot(res, type= type, bySpecies = TRUE)
ggplot2::ggsave(filename = file.path(out_plots, paste0(type, ".png")),
                plot = p)
p
```

## Gross photosynthesis per leaf
```{r eval = params$model=="spwb", fig.height=6, fig.width=8}
type <- "GrossPhotosynthesisPerLeaf"
p <-plot(res, type= type, bySpecies = TRUE)
ggplot2::ggsave(filename = file.path(out_plots, paste0(type, ".png")),
                plot = p)
p
```

## Plant stress
```{r eval = params$model=="spwb", fig.height=6, fig.width=8}
type <- "PlantStress"
p <-plot(res, type= type, bySpecies = TRUE)
ggplot2::ggsave(filename = file.path(out_plots, paste0(type, ".png")),
                plot = p)
p
```

## Stem PLC
```{r eval = params$model=="spwb", fig.height=6, fig.width=8}
type <- "StemPLC"
p <-plot(res, type= type, bySpecies = TRUE)
ggplot2::ggsave(filename = file.path(out_plots, paste0(type, ".png")),
                plot = p)
p
```

# Evaluation

## Soil moisture
```{r eval = eval_REW}
medfate::evaluation_stats(res, site_data$measuredData, type="REW")
```


```{r eval = eval_REW, fig.height=6, fig.width=8}
p<-medfate::evaluation_plot(res, site_data$measuredData, type="REW")
ggplot2::ggsave(filename = file.path(out_evalplots, paste0("REW_dynamics.png")),
                plot = p)
p
```

```{r eval = eval_REW, fig.height=6, fig.width=8}
p<-medfate::evaluation_plot(res, site_data$measuredData, type="REW", plotType = "scatter")
ggplot2::ggsave(filename = file.path(out_evalplots, paste0("REW_scatter.png")),
                plot = p)
p
```

## Plant transpiration

```{r}
cohNames <- row.names(input_object$cohorts)
df<-NULL
cohNamesOut <- character()
for(i in 1:length(cohNames)) {
  measured_var <- paste0("E_", cohNames[i])
  if(measured_var %in% names(site_data$measuredData)) {
      v<-medfate::evaluation_stats(res, site_data$measuredData, type= "E", cohort = cohNames[i])
      if(is.null(df)) df <- v
      else df <- cbind(df, v)
      cohNamesOut <-c(cohNamesOut, cohNames[i])
  }
}
if(!is.null(df)) {
  df <- as.data.frame(t(df), row.names = cohNamesOut)
  print(df)
}
```

```{r fig.keep='all'}
for(i in 1:length(cohNames)) {
  measured_var <- paste0("E_", cohNames[i])
  if(measured_var %in% names(site_data$measuredData)) {
    if(sum(is.na(site_data$measuredData[[measured_var]]))< nrow(site_data$measuredData)) {
      p<-medfate::evaluation_plot(res, site_data$measuredData, 
                                cohort = cohNames[i],
                                type="E", plotType = "dynamics")
      ggplot2::ggsave(filename = file.path(out_evalplots,
                                         paste0(measured_var,"_dynamics.png")),
                    plot = p)
      print(p)
      p<-medfate::evaluation_plot(res, site_data$measuredData, 
                                cohort = cohNames[i],
                                type="E", plotType = "scatter")
      ggplot2::ggsave(filename = file.path(out_evalplots,
                                         paste0(measured_var,"_scatter.png")),
                    plot = p)
      print(p)
    }
  }
}
```

## Leaf water potentials

```{r}
cohNames <- row.names(input_object$cohorts)
df<-NULL
cohNamesOut <- character()
for(i in 1:length(cohNames)) {
  measured_var <- paste0("MD_", cohNames[i])
  if(measured_var %in% names(site_data$measuredData)) {
      v<-medfate::evaluation_stats(res, site_data$measuredData, type= "WP", cohort = cohNames[i])
      if(is.null(df)) df <- v
      else df <- rbind(df, v)
      cohNamesOut <-c(cohNamesOut, cohNames[i])
  }
}
if(!is.null(df)) {
  print(df)
}
```

```{r fig.keep='all'}
for(i in 1:length(cohNames)) {
  measured_out <- paste0("WP_", cohNames[i])
  measured_var <- paste0("MD_", cohNames[i])
  if(measured_var %in% names(site_data$measuredData)) {
    if(sum(is.na(site_data$measuredData[[measured_var]]))< nrow(site_data$measuredData)) {
      p<-medfate::evaluation_plot(res, site_data$measuredData, 
                                cohort = cohNames[i],
                                type="WP", plotType = "dynamics")
      ggplot2::ggsave(filename = file.path(out_evalplots,
                                         paste0(measured_var,"_dynamics.png")),
                    plot = p)
      print(p)
      p<-medfate::evaluation_plot(res, site_data$measuredData, 
                                cohort = cohNames[i],
                                type="WP", plotType = "scatter")
      ggplot2::ggsave(filename = file.path(out_evalplots,
                                         paste0(measured_out,"_scatter.png")),
                    plot = p)
      print(p)
    }
  }
}
```

# Input object

```{r input, collapse=FALSE}
  print(input_object)
```


# Session Info

```{r session_info}
# printing session info
devtools::session_info()
```

